name: Build GH Page
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Converts Markdown to HTML
        uses: jaywcjlove/markdown-to-html-cli@v4
        with:
          github-corners: https://github.com/LeonStoldt/GCP_Professional_Cloud_Developer